(function() {
  exports.SYNC_MESSAGE = 's'.charCodeAt(0);
  exports.WELCOME_MESSAGE = 'W'.charCodeAt(0);
  exports.CREATE_MESSAGE = 'C'.charCodeAt(0);
  exports.DESTROY_MESSAGE = 'D'.charCodeAt(0);
  exports.MAPCHANGE_MESSAGE = 'M'.charCodeAt(0);
  exports.UPDATE_MESSAGE = 'U'.charCodeAt(0);
  exports.TINY_UPDATE_MESSAGE = 'u'.charCodeAt(0);
  exports.SOUNDEFFECT_MESSAGE = 'S'.charCodeAt(0);
  exports.START_TURNING_CCW = 'L';
  exports.STOP_TURNING_CCW = 'l';
  exports.START_TURNING_CW = 'R';
  exports.STOP_TURNING_CW = 'r';
  exports.START_ACCELERATING = 'A';
  exports.STOP_ACCELERATING = 'a';
  exports.START_BRAKING = 'B';
  exports.STOP_BRAKING = 'b';
  exports.START_SHOOTING = 'S';
  exports.STOP_SHOOTING = 's';
  exports.INC_RANGE = 'I';
  exports.DEC_RANGE = 'D';
  exports.BUILD_ORDER = 'O';
}).call(this);
